/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Same JSON line protocol as `inaricode-engine ipc` stdin/stdout, but synchronous from JS. */
export declare function ipcRequest(line: string): string
